version: '3'

services:
    test-autoremove-image:
        # image: 'gcr.io/rd-resources/nginx:alpine-1'
        build: 
            context: .
        ports:
            - "8099:80"
        restart: always
        tty: true
        # command: bash -c "chmod 777 /start.sh; sh /start.sh;"
    